# Generated by Django 5.1.3 on 2025-04-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlmacenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField(verbose_name='usuario')),
                ('id_cuestionario', models.IntegerField(verbose_name='cuestionario')),
                ('no_pregunta', models.IntegerField(verbose_name='no. pregunta')),
                ('id_respuesta', models.IntegerField(verbose_name='respuesta')),
                ('id_poblacion', models.IntegerField()),
                ('id_sexo', models.IntegerField()),
                ('id_nivel_educativo', models.IntegerField()),
                ('id_ingresos', models.IntegerField()),
                ('id_situacion_laboral', models.IntegerField()),
            ],
            options={
                'verbose_name': 'respuesta almacen',
                'verbose_name_plural': 'respuestas almacen',
                'db_table': 'respuestas_dw',
            },
        ),
        migrations.CreateModel(
            name='ProgresoUsuarioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField()),
                ('progreso', models.JSONField()),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'progreso usuario',
                'verbose_name_plural': 'progresos de usuario',
                'db_table': 'progreso_usuario',
            },
        ),
        migrations.CreateModel(
            name='RespuestasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField(verbose_name='id usuario')),
                ('id_cuestionario', models.IntegerField(verbose_name='id del cuestionario')),
                ('respuestas', models.JSONField(verbose_name='respuestas usuario')),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Respuesta del usuario',
                'verbose_name_plural': 'Respuestas de los usuarios',
                'db_table': 'respuestas_usuario',
            },
        ),
    ]
