# Generated by Django 5.1.3 on 2025-04-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlmacenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField(verbose_name='usuario')),
                ('id_cuestionario', models.IntegerField(verbose_name='cuestionario')),
                ('no_pregunta', models.IntegerField(verbose_name='no. pregunta')),
                ('id_respuesta', models.IntegerField(verbose_name='respuesta')),
                ('id_poblacion', models.IntegerField()),
                ('id_sexo', models.IntegerField()),
                ('id_nivel_educativo', models.IntegerField()),
                ('id_ingresos', models.IntegerField()),
                ('id_situacion_laboral', models.IntegerField()),
            ],
            options={
                'verbose_name': 'respuesta almacen',
                'verbose_name_plural': 'respuestas almacen',
                'db_table': 'respuestas_dw',
            },
        ),
    ]
