# Generated by Django 5.1.3 on 2025-05-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respuestas_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosGeneralesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.IntegerField()),
                ('situacion_laboral', models.IntegerField()),
                ('ingresos', models.IntegerField()),
                ('sexo', models.IntegerField()),
                ('poblacion', models.IntegerField()),
                ('nivel_educativo', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'respuestas_datos_generales',
            },
        ),
    ]
