# Generated by Django 5.1.3 on 2025-05-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respuestas_app', '0002_datosgeneralesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosgeneralesmodel',
            name='usuario',
            field=models.IntegerField(unique=True),
        ),
    ]
